// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV71nhcZeW0UkLE6Ar1nf7g7XL9LbTefA',
    appId: '1:297039140091:web:881ab1b0489264eb29cc5e',
    messagingSenderId: '297039140091',
    projectId: 'fir-auth-dc1f8',
    authDomain: 'fir-auth-dc1f8.firebaseapp.com',
    databaseURL: 'https://fir-auth-dc1f8-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-dc1f8.appspot.com',
    measurementId: 'G-5RT5JSBX4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuGiUBKQxAxxv6b1boHxI2KkUAKWqB3u0',
    appId: '1:297039140091:android:f9d4764ee4ae4c2f29cc5e',
    messagingSenderId: '297039140091',
    projectId: 'fir-auth-dc1f8',
    databaseURL: 'https://fir-auth-dc1f8-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-dc1f8.appspot.com',
  );
}
